import { type BountiesSelect } from '@/prisma/models/Bounties';

export const publicListingDetailsSelect = {
  id: true,
  title: true,
  slug: true,
  description: true,
  deadline: true,
  commitmentDate: true,
  eligibility: true,
  status: true,
  token: true,
  rewardAmount: true,
  rewards: true,
  maxBonusSpots: true,
  sponsorId: true,
  isPublished: true,
  skills: true,
  type: true,
  requirements: true,
  isWinnersAnnounced: true,
  region: true,
  pocSocials: true,
  publishedAt: true,
  isPrivate: true,
  agentAccess: true,
  hackathonId: true,
  compensationType: true,
  maxRewardAsk: true,
  minRewardAsk: true,
  isFndnPaying: true,
  winnersAnnouncedAt: true,
  isPro: true,
  sponsor: {
    select: {
      name: true,
      logo: true,
      slug: true,
      url: true,
      entityName: true,
      isVerified: true,
      isCaution: true,
    },
  },
  poc: {
    select: {
      id: true,
      firstName: true,
      lastName: true,
      username: true,
      photo: true,
    },
  },
  Hackathon: {
    select: {
      logo: true,
      altLogo: true,
      startDate: true,
      deadline: true,
      name: true,
      description: true,
      slug: true,
      announceDate: true,
      sponsorId: true,
      Sponsor: {
        select: {
          name: true,
          logo: true,
          slug: true,
          url: true,
          entityName: true,
          isVerified: true,
          isCaution: true,
        },
      },
    },
  },
} satisfies BountiesSelect;
