import { Regions } from '@prisma/client';

export const Superteams = [
  {
    name: 'Superteam India',
    bg: `/assets/category_assets/bg/content.png`,
    color: '#FEFBA8',
    icons: '/assets/superteams/india.jpg',
    region: Regions.INDIA,
    displayValue: 'India',
    country: ['India'],
  },
  {
    name: 'Superteam Germany',
    bg: `/assets/category_assets/bg/backend.png`,
    color: '#FEB8A8',
    icons: '/assets/superteams/germany.jpg',
    region: Regions.GERMANY,
    displayValue: 'Germany',
    country: ['Germany'],
  },
  {
    name: 'Superteam UK',
    bg: `/assets/category_assets/bg/community.png`,
    color: '#BFA8FE',
    icons: '/assets/superteams/uk.png',
    region: Regions.UK,
    displayValue: 'UK',
    country: ['United Kingdom'],
  },
  {
    name: 'Superteam Turkey',
    bg: `/assets/category_assets/bg/design.png`,
    color: '#FEEBA8',
    icons: '/assets/superteams/turkey.jpg',
    region: Regions.TURKEY,
    displayValue: 'Turkey',
    country: ['Turkey'],
  },
  {
    name: 'Superteam Vietnam',
    bg: `/assets/category_assets/bg/frontend.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/vietnam.png',
    region: Regions.VIETNAM,
    displayValue: 'Vietnam',
    country: ['Vietnam'],
  },
  {
    name: 'Superteam UAE',
    bg: `/assets/category_assets/bg/growth.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/uae.png',
    region: Regions.UAE,
    displayValue: 'UAE',
    country: ['United Arab Emirates'],
  },
  {
    name: 'Superteam Nigeria',
    bg: `/assets/category_assets/bg/content.png`,
    color: '#F5A8ED',
    icons: '/assets/superteams/nigeria.png',
    region: Regions.NIGERIA,
    displayValue: 'Nigeria',
    country: ['Nigeria'],
  },
  {
    name: 'Superteam Brazil',
    bg: `/assets/category_assets/bg/backend.png`,
    color: '#FEEBA8',
    icons: '/assets/superteams/brazil.png',
    region: Regions.BRAZIL,
    displayValue: 'Brazil',
    country: ['Brazil'],
  },
  {
    name: 'Superteam Malaysia',
    bg: `/assets/category_assets/bg/community.png`,
    color: '#BFA8FE',
    icons: '/assets/superteams/malaysia.jpg',
    region: Regions.MALAYSIA,
    displayValue: 'Malaysia',
    country: ['Malaysia'],
  },
  {
    name: 'Superteam Balkan',
    bg: `/assets/category_assets/bg/design.png`,
    color: '#FEEBA8',
    icons: '/assets/superteams/balkan.jpeg',
    region: Regions.BALKAN,
    displayValue: 'Balkan',
    country: [
      'Albania',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Croatia',
      'Kosovo',
      'Montenegro',
      'North Macedonia',
      'Romania',
      'Serbia',
      'Slovenia',
    ],
  },
  {
    name: 'Superteam Philippines',
    bg: `/assets/category_assets/bg/frontend.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/philippines.png',
    region: Regions.PHILIPPINES,
    displayValue: 'Philippines',
    country: ['Philippines'],
  },
  {
    name: 'Superteam Japan',
    bg: `/assets/category_assets/bg/growth.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/japan.png',
    region: Regions.JAPAN,
    displayValue: 'Japan',
    country: ['Japan'],
  },
  {
    name: 'Superteam France',
    bg: `/assets/category_assets/bg/content.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/france.png',
    region: Regions.FRANCE,
    displayValue: 'France',
    country: ['France'],
  },
  {
    name: 'Superteam Mexico',
    bg: `/assets/category_assets/bg/backend.png`,
    color: '#A8FEA8',
    icons: '/assets/superteams/mexico.jpg',
    region: Regions.MEXICO,
    displayValue: 'Mexico',
    country: ['Mexico'],
  },
];
