import { ASSET_URL } from './ASSET_URL';

export interface Token {
  tokenName: string;
  tokenSymbol: string;
  mintAddress: string;
  icon: string;
  decimals: number;
}

export const tokenList: Token[] = [
  {
    tokenName: 'USDC',
    tokenSymbol: 'USDC',
    mintAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/3408.png',
    decimals: 6,
  },
  {
    tokenName: 'Solana (SOL)',
    tokenSymbol: 'SOL',
    mintAddress: 'So11111111111111111111111111111111111111112',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/16116.png',
    decimals: 9,
  },
  {
    tokenName: 'JUP',
    tokenSymbol: 'JUP',
    mintAddress: 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/29210.png',
    decimals: 6,
  },
  {
    tokenName: 'BONK',
    tokenSymbol: 'BONK',
    mintAddress: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    icon: 'https://assets.coingecko.com/coins/images/28600/standard/bonk.jpg?1696527587',
    decimals: 5,
  },
  {
    tokenName: 'ISC',
    tokenSymbol: 'ISC',
    mintAddress: 'J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD',
    icon: 'https://res.cloudinary.com/dgvnuwspr/image/upload/v1683200072/sponsors/International%20Stable%20Currency.png',
    decimals: 6,
  },
  {
    tokenName: 'STEP',
    tokenSymbol: 'STEP',
    mintAddress: 'StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT',
    icon: 'https://assets.coingecko.com/coins/images/14988/small/step.png?1619274762',
    decimals: 9,
  },
  {
    tokenName: 'Pyth Network (PYTH)',
    tokenSymbol: 'PYTH',
    mintAddress: 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/28177.png',
    decimals: 6,
  },
  {
    tokenName: 'Kamino (KMNO)',
    tokenSymbol: 'KMNO',
    mintAddress: 'KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS',
    icon: ASSET_URL + '/coins/kamino.png',
    decimals: 6,
  },
  {
    tokenName: 'Jito (JTO)',
    tokenSymbol: 'JTO',
    mintAddress: 'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/28541.png',
    decimals: 9,
  },
  {
    tokenName: 'Metaplex (MPLX)',
    tokenSymbol: 'MPLX',
    mintAddress: 'METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/21870.png',
    decimals: 6,
  },
  {
    tokenName: 'Send (SEND)',
    tokenSymbol: 'SEND',
    mintAddress: 'SENDdRQtYMWaQrBroBrJ2Q53fgVuq95CV9UPGEvpCxa',
    icon: 'https://assets.coingecko.com/coins/images/39222/standard/photo1719676966.jpeg?1721182505',
    decimals: 6,
  },
  {
    tokenName: 'PayPal USD (PYUSD)',
    tokenSymbol: 'PYUSD',
    mintAddress: '2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/27772.png',
    decimals: 6,
  },
  {
    tokenName: 'Drift',
    tokenSymbol: 'DRIFT',
    mintAddress: 'DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/31278.png',
    decimals: 6,
  },
  {
    tokenName: 'SAROS',
    tokenSymbol: 'SAROS',
    mintAddress: 'SarosY6Vscao718M4A778z4CGtvcwcGef5M9MEH1LGL',
    icon: 'https://assets.coingecko.com/coins/images/34594/standard/saros-token-logo.png?1705476813',
    decimals: 6,
  },
  {
    tokenName: 'Samoyed Coin (SAMO)',
    tokenSymbol: 'SAMO',
    mintAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    icon: 'https://assets.coingecko.com/coins/images/15051/standard/IXeEj5e.png?1696514710',
    decimals: 9,
  },
  {
    tokenName: 'Pax Dollar (USDP)',
    tokenSymbol: 'USDP',
    mintAddress: 'HVbpJAQGNpkgBaYBZQBR1t7yFdvaYVp2vCQQfKKEN4tM',
    icon: 'https://assets.coingecko.com/coins/images/6013/standard/Pax_Dollar.png?1696506427',
    decimals: 6,
  },
  {
    tokenName: 'Zeus (ZEUS)',
    tokenSymbol: 'ZEUS',
    mintAddress: 'ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/30391.png',
    decimals: 6,
  },
  {
    tokenName: 'SynesisOne (SNS)',
    tokenSymbol: 'SNS',
    mintAddress: 'SNSNkV9zfG5ZKWQs6x4hxvBRV6s8SqMfSGCtECDvdMd',
    icon: 'https://assets.coingecko.com/coins/images/23289/standard/sns.png?1696522507',
    decimals: 9,
  },
  {
    tokenName: "Dean's List",
    tokenSymbol: 'DEAN',
    mintAddress: 'Ds52CDgqdWbTWsua1hgT3AuSSy4FNx2Ezge1br3jQ14a',
    icon: 'https://assets.coingecko.com/coins/images/36197/standard/logo_dl.png?1710811437',
    decimals: 6,
  },
  {
    tokenName: 'Assai',
    tokenSymbol: 'ASSAI',
    mintAddress: '12XbSPVc5hmWjKUzf5ExTysM2pEL3tM953YkMXmLWkGd',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/35018.png',
    decimals: 9,
  },
  {
    tokenName: 'Ore',
    tokenSymbol: 'ORE',
    mintAddress: 'oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32782.png',
    decimals: 9,
  },
  {
    tokenName: 'USDT',
    tokenSymbol: 'USDT',
    mintAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
    decimals: 6,
  },
  {
    tokenName: 'mSOL',
    tokenSymbol: 'mSOL',
    mintAddress: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11461.png',
    decimals: 9,
  },
  {
    tokenName: 'UXD Stablecoin (UXD)',
    tokenSymbol: 'UXD',
    mintAddress: '7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/17535.png',
    decimals: 6,
  },
  {
    tokenName: 'Solayer USD (sUSD)',
    tokenSymbol: 'sUSD',
    mintAddress: 'susdabGDNbhrnCa6ncrYo81u4s9GM8ecK2UwMyZiq4X',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/35429.png',
    decimals: 6,
  },
  {
    tokenName: 'Raydium (RAY)',
    tokenSymbol: 'RAY',
    mintAddress: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8526.png',
    decimals: 6,
  },
  {
    tokenName: 'Saber (SBR)',
    tokenSymbol: 'SBR',
    mintAddress: 'Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11181.png',
    decimals: 6,
  },
  {
    tokenName: 'KIWI',
    tokenSymbol: 'KIWI',
    mintAddress: '66Qq2qS67K4L5xQ3xUTinCyxzdPeZQG1R1ipK8jrY7gc',
    icon: 'https://bafkreibcamcjwo5z3itvybznrdtb3fgeiplfy36izu75jygxkt7jzoq4ju.ipfs.nftstorage.link/',
    decimals: 5,
  },
  {
    tokenName: 'EUROe Stablecoin (EUROe)',
    tokenSymbol: 'EUROe',
    mintAddress: '2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg',
    icon: 'https://assets.coingecko.com/coins/images/28913/standard/euroe-200x200-round.png?1696527889',
    decimals: 6,
  },
  {
    tokenName: 'Solend (SLND)',
    tokenSymbol: 'SLND',
    mintAddress: 'SLNDpmoWTVADgEdndyvWzroNL7zSi1dF9PC3xHGtPwp',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/13524.png',
    decimals: 6,
  },
  {
    tokenName: 'Coin98 (C98)',
    tokenSymbol: 'C98',
    mintAddress: 'C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/10903.png',
    decimals: 6,
  },
  {
    tokenName: 'Serum (SRM)',
    tokenSymbol: 'SRM',
    mintAddress: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6187.png',
    decimals: 6,
  },
  {
    tokenName: 'DUST Protocol (DUST)',
    tokenSymbol: 'DUST',
    mintAddress: 'DUSTawucrTsGU8hcqRdHDCbuYhCPADMLM2VcCb8VnFnQ',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/18802.png',
    decimals: 9,
  },
  {
    tokenName: 'Bonfida (FIDA)',
    tokenSymbol: 'FIDA',
    mintAddress: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7978.png',
    decimals: 6,
  },
  {
    tokenName: 'Orca (ORCA)',
    tokenSymbol: 'ORCA',
    mintAddress: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11165.png',
    decimals: 6,
  },
  {
    tokenName: 'Helium (HNT)',
    tokenSymbol: 'HNT',
    mintAddress: 'hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5665.png',
    decimals: 8,
  },
  {
    tokenName: 'Helium Mobile (MOBILE)',
    tokenSymbol: 'MOBILE',
    mintAddress: 'mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/24600.png',
    decimals: 6,
  },
  {
    tokenName: 'Helium IOT (IOT)',
    tokenSymbol: 'IOT',
    mintAddress: 'iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/24686.png',
    decimals: 6,
  },
  {
    tokenName: 'Gary (GARY)',
    tokenSymbol: 'GARY',
    mintAddress: '8c71AvjQeKKeWRe8jtTGG1bJ2WiYXQdbjqFbUfhHgSVk',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/21046.png',
    decimals: 9,
  },
  {
    tokenName: 'Blaze (BLZE)',
    tokenSymbol: 'BLZE',
    mintAddress: 'BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA',
    icon: 'https://assets.coingecko.com/coins/images/28392/standard/blze.png?1696527391',
    decimals: 9,
  },
  {
    tokenName: 'META (META)',
    tokenSymbol: 'META',
    mintAddress: 'METADDFL6wWMWEoKTFJwcThTbUmtarRJZjRpzUvkxhr',
    icon: 'https://avatars.githubusercontent.com/u/107701386?s=200&v=4',
    decimals: 9,
  },
  {
    tokenName: 'ZETA (ZEX)',
    tokenSymbol: 'ZEX',
    mintAddress: 'ZEXy1pqteRu3n13kdyh4LwPQknkFk3GzmMYMuNadWPo',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/32002.png',
    decimals: 6,
  },
  {
    tokenName: 'Degod (DEGOD)',
    tokenSymbol: 'DEGOD',
    mintAddress: 'degod39zqQWzpG6h4b7SJLLTCFE6FeZnZD8BwHBFxaN',
    icon: ASSET_URL + '/coins/degods.png',
    decimals: 6,
  },
  {
    tokenName: 'DevWifHat (DWH)',
    tokenSymbol: 'DWH',
    mintAddress: 'DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o',
    icon: ASSET_URL + '/coins/dwh.png',
    decimals: 6,
  },
  {
    tokenName: 'ChiitanCoin (CTAN)',
    tokenSymbol: 'CTAN',
    mintAddress: 'A3gMddXMAhmc3P9dLjHv2n6ywWWzpGZbRCH6y8sta8ug',
    icon: ASSET_URL + '/coins/ctan.png',
    decimals: 9,
  },
  {
    tokenName: 'Utgard (UTG)',
    tokenSymbol: 'UTG',
    mintAddress: 'FPZsqAgtwf58GmJMctZGSu9RaXiGAmQLL6ZtKUUewm7k',
    icon: ASSET_URL + '/coins/utg.png',
    decimals: 9,
  },
  {
    tokenName: 'Vin (VIN)',
    tokenSymbol: 'VIN',
    mintAddress: '6B2X4NmSsmkiT8ytFEVt15igRSgsKNGZ3j3WWeidupE8',
    icon: ASSET_URL + '/coins/vin.png',
    decimals: 9,
  },
  {
    tokenName: 'Octokn (OTK)',
    tokenSymbol: 'OTK',
    mintAddress: 'octo82drBEdm8CSDaEKBymVn86TBtgmPnDdmE64PTqJ',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/24381.png',
    decimals: 9,
  },
  {
    tokenName: 'deBridge',
    tokenSymbol: 'DBR',
    mintAddress: 'DBRiDgJAMsM95moTzJs7M9LnkGErpbv9v6CUR1DXnUu5',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/31528.png',
    decimals: 6,
  },
  {
    tokenName: 'Adrena',
    tokenSymbol: 'ADX',
    mintAddress: 'AuQaustGiaqxRvj2gtCdrd22PBzTn8kM3kEPEkZCtuDw',
    icon: 'https://assets.coingecko.com/coins/images/50363/standard/adrena_logo_adx_color_200x200.png?1727331561',
    decimals: 6,
  },
  {
    tokenName: 'Nosana',
    tokenSymbol: 'NOS',
    mintAddress: 'nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7',
    icon: 'https://assets.coingecko.com/coins/images/22553/standard/POfb_I4u_400x400.jpg?1696521873',
    decimals: 6,
  },
  {
    tokenName: 'Edwin',
    tokenSymbol: 'EDWIN',
    mintAddress: 'GPrg1CgbBvAJS2SCuf9gF7NmQYsWudfyfWy5SUzypump',
    icon: 'https://assets.coingecko.com/coins/images/53937/standard/logo-background.png?1737783340',
    decimals: 6,
  },
  {
    tokenName: 'Blockasset',
    tokenSymbol: 'BLOCK',
    mintAddress: 'NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk',
    icon: 'https://assets.coingecko.com/coins/images/21332/standard/Blockasset_Square.png?1712955829',
    decimals: 6,
  },
  {
    tokenName: 'Magic Eden',
    tokenSymbol: 'ME',
    mintAddress: 'MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u',
    icon: 'https://assets.coingecko.com/coins/images/39850/standard/_ME_Profile_Dark_2x.png?1734013082',
    decimals: 6,
  },
  {
    tokenName: 'Zeus Network zBTC',
    tokenSymbol: 'zBTC',
    mintAddress: 'zBTCug3er3tLyffELcvDNrKkCymbPWysGcWihESYfLg',
    icon: 'https://assets.coingecko.com/coins/images/55011/standard/zBTC.png?1743161954',
    decimals: 8,
  },
  {
    tokenName: 'Global Dollar (USDG)',
    tokenSymbol: 'USDG',
    mintAddress: '2u1tszSeqZ3qBWF3uNGPFc8TzMk2tdiwknnRMWGWjGWH',
    icon: 'https://assets.coingecko.com/coins/images/51281/standard/GDN_USDG_Token_200x200.png?1730484111',
    decimals: 6,
  },
  {
    tokenName: 'DMCP',
    tokenSymbol: 'DMCP',
    mintAddress: '81YHAzq9yfptVbNTHiYuMVKVQ6ZNs3XeQFFENnNUpump',
    icon: 'https://earn.superteam.fun/assets/dollar.svg',
    decimals: 6,
  },
  {
    tokenName: 'Polymtrade',
    tokenSymbol: 'PM',
    mintAddress: '3BWA5RBXyPXuMGZmVL8Snefu573FMJNGpsVi79baiBLV',
    icon: 'https://assets.coingecko.com/coins/images/66546/standard/polymtrade.png?1749711691',
    decimals: 9,
  },
  {
    tokenName: 'SpineDAO',
    tokenSymbol: 'SPINE',
    mintAddress: 'spinezMPKxkBpf4Q9xET2587fehM3LuKe4xoAoXtSjR',
    icon: 'https://assets.coingecko.com/coins/images/55920/standard/TOken_SPine_b.png',
    decimals: 9,
  },
  {
    tokenName: 'aeroSOL',
    tokenSymbol: 'aeroSOL',
    mintAddress: 'aeroXvCT6tjGVNyTvZy86tFDwE4sYsKCh7FbNDcrcxF',
    icon: 'https://assets.coingecko.com/coins/images/40123/standard/Logo_-_Bright_%284%29.png',
    decimals: 9,
  },
  {
    tokenName: 'JuliaOS',
    tokenSymbol: 'JOS',
    mintAddress: 'JosjEXh69RckgSs2AWsN1xN8zmiSHxBuJjHLURJnHhg',
    icon: 'https://assets.coingecko.com/coins/images/55336/standard/JuliaOS-logo.png?1745507802',
    decimals: 6,
  },
  {
    tokenName: 'USD Star',
    tokenSymbol: 'USD*',
    mintAddress: 'BenJy1n3WTx9mTjEvy63e8Q1j4RqUc6E4VBMz3ir4Wo6',
    icon: 'https://res.cloudinary.com/dgvnuwspr/image/upload/v1754053412/2025-08-01_18.30.41_utc1fs.jpg',
    decimals: 6,
  },
  {
    tokenName: 'Marinade',
    tokenSymbol: 'MNDE',
    mintAddress: 'MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/128x128/13803.png',
    decimals: 9,
  },
  {
    tokenName: 'Swop.Meme',
    tokenSymbol: 'SWOP',
    mintAddress: 'AhhtUFVLUSDxgsPTuky7JXEi92e3QcqnagfgZoDSjups',
    icon: '',
    decimals: 6,
  },
  {
    tokenName: 'Sonic SVM',
    tokenSymbol: 'SONIC',
    mintAddress: 'SonicxvLud67EceaEzCLRnMTBqzYUUYNr93DBkBdDES',
    icon: 'https://assets.coingecko.com/coins/images/53061/standard/Token.png?1735169618',
    decimals: 9,
  },
  {
    tokenName: 'XNET Mobile',
    tokenSymbol: 'XNET',
    mintAddress: 'xNETbUB7cRb3AAu2pNG2pUwQcJ2BHcktfvSB8x1Pq6L',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/32753.png',
    decimals: 8,
  },
  {
    tokenName: 'PITE',
    tokenSymbol: 'PITE',
    mintAddress: 'piteafefafae',
    icon: '',
    decimals: 6,
  },
];
