import { Sparkles } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { type BountyType } from '@/generated/prisma/enums';
import { BountyIcon } from '@/svg/bounty-icon';
import { ProjectIcon } from '@/svg/project-icon';

import { Templates } from './Templates';
import { AutoGenerateDropdownType } from './Type';

interface AutoGenerateFormProps {
  type: BountyType;
  setType: (type: BountyType) => void;
  onBack?: () => void;
  onGenerate?: (data: {
    description: string;
    type: string;
    template?: string;
  }) => void;
}

export function AutoGenerateForm({
  type,
  setType,
  onBack: _onBack,
  onGenerate,
}: AutoGenerateFormProps) {
  const [description, setDescription] = useState('');
  const [_selectedTemplate, _setSelectedTemplate] = useState<string>('');

  const handleGenerate = () => {
    onGenerate?.({
      description,
      type,
      template: _selectedTemplate,
    });
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {type === 'bounty' ? (
            <BountyIcon
              styles={{ width: '1.2rem', height: '1.2rem' }}
              className="fill-gray-500"
            />
          ) : (
            <ProjectIcon
              styles={{ width: '1.2rem', height: '1.2rem' }}
              className="fill-gray-500"
            />
          )}
          <h2 className="text-lg font-medium">Generate your {type} with AI</h2>
        </div>
        <div>
          <AutoGenerateDropdownType type={type} setType={setType} />
        </div>
      </div>

      <div className="space-y-4">
        <Textarea
          placeholder="Briefly describe the scope of your task"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="min-h-55 w-full resize-none"
        />
      </div>

      <div>
        <Templates
          type={type}
          onSelectTemplate={() => {}}
          onUnselectTemplate={() => {}}
        />
      </div>

      <div className="flex justify-end">
        <Button
          onClick={handleGenerate}
          disabled={!description.trim()}
          className="w-fit"
        >
          <Sparkles />
          Generate Lisiing
        </Button>
      </div>
    </div>
  );
}
