import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from '@/components/ui/select';
import { type BountyType } from '@/generated/prisma/enums';
import { BountyIcon } from '@/svg/bounty-icon';
import { ProjectIcon } from '@/svg/project-icon';
interface AutoGenerateTypeProps {
  setType: (type: BountyType) => void;
  type: BountyType;
}
export function AutoGenerateStageType({ setType }: AutoGenerateTypeProps) {
  return (
    <div className="space-y-4 p-4">
      <h2 className="text-lg font-medium">Select type of listing</h2>
      <div className="grid grid-cols-2 gap-4">
        <Button
          className="flex h-55 flex-col gap-4 whitespace-normal text-slate-500 hover:text-slate-500"
          variant="outline"
          onClick={() => setType('bounty')}
        >
          <BountyIcon
            className="fill-slate-500"
            styles={{
              width: '3rem',
              height: '3rem',
            }}
          />
          <span className="flex max-w-3/4 flex-col gap-1">
            <h3 className="text-base font-medium text-slate-900">Bounty</h3>
            <p className="text-sm font-normal">
              Get multiple submissions for your task, and reward the best work
            </p>
          </span>
        </Button>
        <Button
          className="flex h-55 flex-col gap-4 whitespace-normal text-slate-500 hover:text-slate-500"
          variant="outline"
          onClick={() => setType('project')}
        >
          <ProjectIcon
            className="fill-slate-500"
            styles={{
              width: '3rem',
              height: '3rem',
            }}
          />
          <span className="flex max-w-3/4 flex-col gap-1">
            <h3 className="text-base font-medium text-slate-900">Project</h3>
            <p className="text-sm font-normal">
              Receive proposals for your work and pick the right candidate
            </p>
          </span>
        </Button>
      </div>
    </div>
  );
}

export function AutoGenerateDropdownType({
  type,
  setType,
}: AutoGenerateTypeProps) {
  return (
    <Select
      value={type}
      onValueChange={(value) => setType(value as 'bounty' | 'project')}
    >
      <SelectTrigger className="h-8 w-auto font-medium text-slate-500">
        <div className="flex items-center gap-2 pr-2">
          {type === 'bounty' ? (
            <BountyIcon
              styles={{ width: '0.9rem', height: '0.9rem' }}
              className="fill-gray-500"
            />
          ) : (
            <ProjectIcon
              styles={{ width: '0.9rem', height: '0.9rem' }}
              className="fill-gray-500"
            />
          )}
          {type === 'bounty' ? 'Bounty' : 'Project'}
        </div>
      </SelectTrigger>
      <SelectContent className="font-medium text-slate-500">
        <SelectItem value="bounty">
          <div className="flex items-center gap-2">
            <BountyIcon
              styles={{ width: '0.9rem', height: '0.9rem' }}
              className="fill-gray-500"
            />
            Bounty
          </div>
        </SelectItem>
        <SelectItem value="project">
          <div className="flex items-center gap-2">
            <ProjectIcon
              styles={{ width: '0.9rem', height: '0.9rem' }}
              className="fill-gray-500"
            />
            Project
          </div>
        </SelectItem>
      </SelectContent>
    </Select>
  );
}
