import { usePrivy } from '@privy-io/react-auth';
import { useQuery } from '@tanstack/react-query';
import { useSetAtom } from 'jotai';
import { Lock, Pencil, PencilLine, Plus, Users } from 'lucide-react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useRouter } from 'next/router';
import posthog from 'posthog-js';
import {
  type ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

import BiListUl from '@/components/icons/BiListUl';
import { type IconType } from '@/components/icons/helpers/GenIcon';
import MdList from '@/components/icons/MdList';
import MdOutlineChatBubbleOutline from '@/components/icons/MdOutlineChatBubbleOutline';
import RiUserSettingsLine from '@/components/icons/RiUserSettingsLine';
import { EntityNameModal } from '@/components/modals/EntityNameModal';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Tooltip } from '@/components/ui/tooltip';
import { JTTG } from '@/constants/Telegram';
import { SolanaWalletProvider } from '@/context/SolanaWallet';
import { useDisclosure } from '@/hooks/use-disclosure';
import { useMediaQuery } from '@/hooks/use-media-query';
import { Default } from '@/layouts/Default';
import { Meta } from '@/layouts/Meta';
import { SponsorContentSkeleton } from '@/layouts/SponsorLayoutSkeleton';
import { useUser } from '@/store/user';
import Sparkle from '@/svg/sparkle';
import { cn } from '@/utils/cn';

import { isAutoGenerateOpenAtom } from '@/features/listing-builder/atoms';
import { isCreateListingAllowedQuery } from '@/features/listing-builder/queries/is-create-allowed';
import { NavItem } from '@/features/sponsor-dashboard/components/NavItems';
import { MobileDesktopOnlyDialog } from '@/features/sponsor-dashboard/components/MobileDesktopOnlyDialog';
import { SelectHackathon } from '@/features/sponsor-dashboard/components/SelectHackathon';
import { SelectSponsor } from '@/features/sponsor-dashboard/components/SelectSponsor';
import { activeHackathonsQuery } from '@/features/sponsor-dashboard/queries/active-hackathons';

const ProListingsAnnouncement = dynamic(
  () =>
    import('@/features/announcements/components/ProListingsAnnouncement').then(
      (m) => m.ProListingsAnnouncement,
    ),
  { ssr: false },
);

const Login = dynamic(
  () => import('@/features/auth/components/Login').then((m) => m.Login),
  { ssr: false },
);

const AutoGenerateDialog = dynamic(
  () =>
    import('@/features/listing-builder/components/AutoGenerate/Dialog').then(
      (m) => m.AutoGenerateDialog,
    ),
  { ssr: false },
);

const CreateListingModal = dynamic(
  () =>
    import('@/features/sponsor-dashboard/components/CreateListingModal').then(
      (m) => m.CreateListingModal,
    ),
  { ssr: false },
);

const SponsorInfoModal = dynamic(
  () =>
    import('@/features/sponsor-dashboard/components/SponsorInfoModal').then(
      (m) => m.SponsorInfoModal,
    ),
  { ssr: false },
);

interface LinkItemProps {
  name: string;
  link?: string;
  icon: IconType;
  isExternal?: boolean;
  posthog?: string;
}

export function SponsorLayout({
  children,
  isCollapsible = false,
}: {
  children: ReactNode;
  isCollapsible?: boolean;
}) {
  const { user, isLoading: isUserLoading } = useUser();
  const { authenticated, ready } = usePrivy();
  const router = useRouter();
  const { isOpen, onOpen, onClose } = useDisclosure();
  const {
    isOpen: isSponsorInfoModalOpen,
    onOpen: onSponsorInfoModalOpen,
    onClose: onSponsorInfoModalClose,
  } = useDisclosure();
  const {
    isOpen: isMobileDesktopOnlyOpen,
    onOpen: onMobileDesktopOnlyOpen,
    onClose: onMobileDesktopOnlyClose,
  } = useDisclosure();

  const [isEntityModalOpen, setIsEntityModalOpen] = useState(false);
  const { query } = router;
  const [isExpanded, setIsExpanded] = useState(() => !isCollapsible);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  const canSelectSponsor =
    user?.role === 'GOD' || (user?.UserSponsors?.length ?? 0) > 0;
  const isTeamSettingsVisible = useMemo(() => {
    if (user?.role === 'GOD') return true;
    const currentSponsorLink = user?.UserSponsors?.find(
      (s) => s.sponsorId === user?.currentSponsorId,
    );
    return currentSponsorLink?.role === 'ADMIN';
  }, [user?.UserSponsors, user?.currentSponsorId, user?.role]);

  const setAutoGenerateOpen = useSetAtom(isAutoGenerateOpenAtom);
  const isMobile = useMediaQuery('(max-width: 767px)');

  const openMobileDesktopOnlyNotice = (flow: 'ai' | 'scratch') => {
    onMobileDesktopOnlyOpen();
    posthog.capture(
      flow === 'ai'
        ? 'new generate with ai_sponsor_mobile_desktop_only'
        : 'new start from scratch_sponsor_mobile_desktop_only',
    );
  };

  const handleMouseEnter = useCallback(() => {
    if (!isCollapsible) return;
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
    timeoutRef.current = setTimeout(() => {
      setIsExpanded(true);
    }, 250);
  }, [isCollapsible]);

  const handleMouseLeave = useCallback(() => {
    if (!isCollapsible) return;
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
    setIsExpanded(false);
  }, [isCollapsible]);

  const open = !!query.open;
  useEffect(() => {
    if (open) {
      setAutoGenerateOpen(true);
    }
  }, [open]);

  const { data: isCreateListingAllowed } = useQuery(
    isCreateListingAllowedQuery,
  );

  const handleEntityClose = () => {
    setIsEntityModalOpen(false);
  };

  useEffect(() => {
    const modalsToShow = async () => {
      if (
        user?.currentSponsorId &&
        (!user?.firstName ||
          !user?.lastName ||
          !user?.username ||
          !user?.telegram)
      ) {
        onSponsorInfoModalOpen();
      } else if (!user?.currentSponsor?.entityName && user?.role !== 'GOD') {
        setIsEntityModalOpen(true);
      } else {
        setIsEntityModalOpen(false);
      }
    };
    modalsToShow();
  }, [user]);

  useEffect(() => {
    if (
      !isUserLoading &&
      ready &&
      authenticated &&
      user &&
      !user?.currentSponsorId
    ) {
      router.push('/earn');
    }
  }, [user, authenticated, ready, isUserLoading]);

  const { data: hackathons } = useQuery({
    ...activeHackathonsQuery(),
    enabled: !!user,
  });

  const isHackathonRoute = useMemo(
    () => router.asPath.startsWith('/earn/dashboard/hackathon'),
    [router.asPath],
  );

  const isLocalProfileVisible = useMemo(() => {
    const sponsorChapterId = user?.currentSponsor?.chapter?.id;
    if (!sponsorChapterId) return false;
    if (user?.role === 'GOD') return true;
    const isCoreMember = user?.people?.type?.toUpperCase() === 'CORE';
    return isCoreMember && user?.people?.chapterId === sponsorChapterId;
  }, [
    user?.currentSponsor?.chapter?.id,
    user?.people?.chapterId,
    user?.people?.type,
    user?.role,
  ]);

  if (ready && !authenticated) {
    return <Login isOpen={true} onClose={() => {}} />;
  }

  const isLoading = !ready || (authenticated && isUserLoading);

  const LinkItems: Array<LinkItemProps> = isHackathonRoute
    ? [
        {
          name: 'All Tracks',
          link: `/hackathon`,
          icon: MdList,
        },
        {
          name: 'Get Help',
          link: JTTG,
          icon: MdOutlineChatBubbleOutline,
          posthog: 'get help_sponsor',
        },
      ]
    : [
        {
          name: 'My Listings',
          link: '/listings',
          icon: BiListUl,
        },
        ...(isTeamSettingsVisible
          ? [
              {
                name: 'Team Settings',
                link: '/team-settings',
                icon: RiUserSettingsLine,
              },
            ]
          : []),
        ...(isLocalProfileVisible
          ? [
              {
                name: 'Local Profiles',
                link: '/local-profiles',
                icon: Users,
              },
            ]
          : []),
        {
          name: 'Edit Profile',
          link: '/sponsor/edit',
          icon: Pencil,
        },
        {
          name: 'FAQ',
          link: '/faq',
          icon: MdOutlineChatBubbleOutline,
          posthog: 'faq_sponsor',
        },
      ];

  const showContent = isHackathonRoute
    ? user?.hackathonId || user?.role === 'GOD'
    : user?.currentSponsor?.id;

  const isAnyModalOpen = isOpen || isSponsorInfoModalOpen || isEntityModalOpen;

  return (
    <SolanaWalletProvider>
      <Default
        className="bg-white"
        meta={
          <Meta
            title="Superteam Earn | Work to Earn in Crypto"
            description="Explore the latest bounties on Superteam Earn, offering opportunities in the crypto space across Design, Development, and Content."
            noIndex
          />
        }
      >
        <SponsorInfoModal
          onClose={onSponsorInfoModalClose}
          isOpen={isSponsorInfoModalOpen}
        />

        <MobileDesktopOnlyDialog
          open={isMobileDesktopOnlyOpen}
          onOpenChange={onMobileDesktopOnlyClose}
          title="Continue on desktop"
          description="Creating and editing listings is optimized for desktop. Please continue on a larger screen to choose a listing type or finish setup."
        />

        {/* {router.pathname === '/dashboard/listings' && (
          <SponsorAnnouncements isAnyModalOpen={isAnyModalOpen} />
        )} */}

        <ProListingsAnnouncement isAnyModalOpen={isAnyModalOpen} />

        <EntityNameModal
          isOpen={isEntityModalOpen}
          onClose={handleEntityClose}
        />

        <div className="flex min-h-[max(100vh,1000px)] flex-col justify-start overflow-x-hidden transition-all duration-300 ease-in-out md:flex-row md:hover:shadow-lg">
          <div
            className={cn(
              'sponsor-dashboard-sidebar overflow-x-hidden border-r border-slate-200 bg-white pt-5 whitespace-nowrap',
              'transition-all duration-300 ease-in-out',
              'transition-shadow hover:shadow-lg',
              'hidden md:flex md:flex-col',
              isCollapsible ? 'fixed' : 'static',
              isExpanded
                ? ['w-64 max-w-64 min-w-64', 'expanded']
                : ['w-20 max-w-20 min-w-20'],
              'top-12 bottom-0 left-0 z-10',
            )}
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
          >
            {canSelectSponsor && (
              <div className={cn('pb-6', isExpanded ? 'pr-4 pl-6' : 'px-4')}>
                {isHackathonRoute ? (
                  <SelectHackathon isExpanded={isExpanded} />
                ) : (
                  <SelectSponsor isExpanded={isExpanded} />
                )}
              </div>
            )}
            <CreateListingModal
              isOpen={isOpen}
              onClose={onClose}
              hackathons={hackathons}
            />
            <AutoGenerateDialog hackathons={hackathons} />
            <div
              className={cn(
                'flex items-center justify-between px-4 pb-6',
                isExpanded ? 'pr-4 pl-6' : 'px-4',
              )}
            >
              {!isHackathonRoute ? (
                <DropdownMenu>
                  <Tooltip
                    content={
                      "Creating a new listing has been temporarily locked for you since you have 5 listings which are 'In Review'. Please announce the winners for such listings to create new listings."
                    }
                    disabled={
                      !(
                        isCreateListingAllowed !== undefined &&
                        isCreateListingAllowed === false &&
                        user?.role !== 'GOD'
                      )
                    }
                  >
                    <DropdownMenuTrigger asChild>
                      <Button
                        className={cn(
                          'ph-no-capture w-full gap-2 py-5.5 text-base',
                          'disabled:cursor-not-allowed disabled:opacity-50',
                        )}
                        disabled={
                          isCreateListingAllowed !== undefined &&
                          isCreateListingAllowed === false &&
                          user?.role !== 'GOD'
                        }
                        variant="default"
                      >
                        <Plus className="h-3 w-3" />
                        <p
                          className={cn(
                            'nav-item-text transition-all duration-200 ease-in-out',
                            isExpanded
                              ? ['static ml-0 opacity-100']
                              : ['absolute -ml-[9999px] opacity-0'],
                          )}
                        >
                          <span>Create New Listing</span>
                        </p>
                        {isCreateListingAllowed !== undefined &&
                          isCreateListingAllowed === false &&
                          user?.role !== 'GOD' && <Lock className="h-4 w-4" />}
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent
                      className="min-w-[200px] font-medium text-slate-500"
                      align="start"
                    >
                      <DropdownMenuItem
                        className="flex items-center justify-between"
                        onClick={() => {
                          if (isMobile) {
                            openMobileDesktopOnlyNotice('ai');
                            return;
                          }
                          posthog.capture('new generate with ai_sponsor');
                          setAutoGenerateOpen(true);
                        }}
                      >
                        <span className="flex items-center gap-2 text-sm">
                          <Sparkle className="h-4 w-4" />
                          Generate with AI
                        </span>
                        <span>
                          <span className="rounded-full bg-emerald-50 px-1.5 py-0.5 text-[0.65rem] text-emerald-600">
                            2m
                          </span>
                        </span>
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        className="flex items-center justify-between"
                        onClick={() => {
                          if (isMobile) {
                            openMobileDesktopOnlyNotice('scratch');
                            return;
                          }
                          posthog.capture('new start from scratch_sponsor');
                          onOpen();
                        }}
                      >
                        <span className="flex items-center gap-2 text-sm">
                          <PencilLine className="h-4 w-4" />
                          Start from Scratch
                        </span>
                        <span>
                          <span className="rounded-full bg-indigo-50 px-1.5 py-0.5 text-[0.65rem] text-indigo-600">
                            10m
                          </span>
                        </span>
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </Tooltip>
                </DropdownMenu>
              ) : (
                <Button
                  asChild
                  className={cn('w-full gap-2 py-5.5 text-base')}
                  variant="default"
                >
                  <Link href="/earn/dashboard/new/?type=hackathon">
                    <Plus className="h-3 w-3" />
                    <p
                      className={cn(
                        'nav-item-text transition-opacity duration-200 ease-in-out',
                        isExpanded
                          ? ['static ml-0 opacity-100']
                          : ['absolute -ml-[9999px] opacity-0'],
                      )}
                    >
                      Create New Track
                    </p>
                  </Link>
                </Button>
              )}
            </div>
            {LinkItems.map((link) => (
              <NavItem
                onClick={() => {
                  if (link.posthog) posthog.capture(link.posthog);
                }}
                className="ph-no-capture"
                key={link.name}
                link={link.link}
                icon={link.icon}
                isExpanded={isExpanded}
              >
                {link.name}
              </NavItem>
            ))}
          </div>
          {(showContent || isLoading) && (
            <div
              className={cn(
                'w-full flex-1 overflow-x-auto bg-white py-5 pr-4 pl-4 pb-20 transition-[margin-left] duration-300 ease-in-out md:pr-8 md:pb-5',
                isCollapsible ? 'md:ml-20' : 'ml-0',
              )}
            >
              {/* Mobile-only top strip: sponsor selector + quick actions */}
              <div className="mb-4 flex flex-col gap-3 md:hidden">
                {canSelectSponsor && (
                  <div className="min-w-0 flex-1">
                    {isHackathonRoute ? (
                      <SelectHackathon isExpanded={true} />
                    ) : (
                      <SelectSponsor isExpanded={true} />
                    )}
                  </div>
                )}
                <div className="flex items-center gap-2">
                  {isTeamSettingsVisible && (
                    <Button
                      asChild
                      size="sm"
                      variant="outline"
                      className="min-w-0 flex-1 gap-1.5 border-slate-200 text-slate-600"
                    >
                      <Link href="/earn/dashboard/team-settings">
                        <Users className="h-3.5 w-3.5" />
                        Team
                      </Link>
                    </Button>
                  )}
                  {!isHackathonRoute ? (
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          className="ph-no-capture min-w-0 flex-1 gap-1.5"
                          size="sm"
                          disabled={
                            isCreateListingAllowed !== undefined &&
                            isCreateListingAllowed === false &&
                            user?.role !== 'GOD'
                          }
                        >
                          <Plus className="h-3.5 w-3.5" />
                          New
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent
                        className="min-w-[200px] font-medium text-slate-500"
                        align="end"
                      >
                        <DropdownMenuItem
                          className="flex items-center justify-between"
                          onClick={() => {
                            if (isMobile) {
                              openMobileDesktopOnlyNotice('ai');
                              return;
                            }
                            posthog.capture('new generate with ai_sponsor');
                            setAutoGenerateOpen(true);
                          }}
                        >
                          <span className="flex items-center gap-2 text-sm">
                            <Sparkle className="h-4 w-4" />
                            Generate with AI
                          </span>
                          <span className="rounded-full bg-emerald-50 px-1.5 py-0.5 text-[0.65rem] text-emerald-600">
                            2m
                          </span>
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          className="flex items-center justify-between"
                          onClick={() => {
                            if (isMobile) {
                              openMobileDesktopOnlyNotice('scratch');
                              return;
                            }
                            posthog.capture('new start from scratch_sponsor');
                            onOpen();
                          }}
                        >
                          <span className="flex items-center gap-2 text-sm">
                            <PencilLine className="h-4 w-4" />
                            Start from Scratch
                          </span>
                          <span className="rounded-full bg-indigo-50 px-1.5 py-0.5 text-[0.65rem] text-indigo-600">
                            10m
                          </span>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  ) : isMobile ? (
                    <Button
                      size="sm"
                      className="min-w-0 flex-1 gap-1.5"
                      onClick={() => {
                        openMobileDesktopOnlyNotice('scratch');
                      }}
                    >
                      <Plus className="h-3.5 w-3.5" />
                      New Track
                    </Button>
                  ) : (
                    <Button size="sm" className="min-w-0 flex-1 gap-1.5" asChild>
                      <Link href="/earn/dashboard/new/?type=hackathon">
                        <Plus className="h-3.5 w-3.5" />
                        New Track
                      </Link>
                    </Button>
                  )}
                </div>
              </div>
              {isLoading ? <SponsorContentSkeleton /> : children}
            </div>
          )}
        </div>

        {/* Mobile bottom navigation */}
        <nav className="fixed bottom-0 left-0 right-0 z-50 flex items-stretch border-t border-slate-200 bg-white md:hidden">
          {LinkItems.map((link) => {
            const Icon = link.icon;
            const resolvedLink = link.link?.startsWith('https://')
              ? link.link
              : `/earn/dashboard${link.link}`;
            const isActive = router.asPath
              .split('?')[0]
              ?.startsWith(resolvedLink || '');
            return (
              <Link
                key={link.name}
                href={resolvedLink || '#'}
                target={link.link?.startsWith('https://') ? '_blank' : undefined}
                rel={
                  link.link?.startsWith('https://')
                    ? 'noopener noreferrer'
                    : undefined
                }
                onClick={() => {
                  if (link.posthog) posthog.capture(link.posthog);
                }}
                className={cn(
                  'flex flex-1 flex-col items-center justify-center gap-0.5 py-2 text-xs font-medium transition-colors',
                  isActive
                    ? 'text-indigo-600'
                    : 'text-slate-500 hover:text-indigo-600',
                )}
              >
                <Icon className="h-5 w-5" />
                <span className="max-w-[60px] truncate text-center leading-tight">
                  {link.name}
                </span>
              </Link>
            );
          })}
        </nav>
      </Default>
    </SolanaWalletProvider>
  );
}
