#!/usr/bin/env node

const { execSync } = require('child_process');

const protected_branch = 'husky-test';
const current_branch = execSync('git symbolic-ref HEAD').toString().trim().split('/').pop();

if (current_branch === protected_branch) {
  const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  });

  readline.question(`You're about to push to ${protected_branch}, is that what you intended? [y/n] `, (answer) => {
    readline.close();
    if (answer.toLowerCase() !== 'y') {
      console.log('Push aborted.');
      process.exit(1);
    }
  });
} else {
  process.exit(0);
}